# Auto-generated by dashTranspileR -- do not edit by hand

#' DashColorscales dash-colorscales component
#' @description DashColorscales is a Dash wrapper for `react-colorscales`. It takes an array of colors, `colorscale`, and displays a UI for modifying it or choosing a new scale.
#' @export
#' @param id The ID used to identify this compnent in Dash callbacks 
#' @param colorscale Optional: Initial colorscale to display. Default is Viridis. 
#' @param nSwatches Optional: Initial number of colors in scale to display. 
#' @param fixSwatches Optional: Set to `True` to fix the number of colors in the scale. 
#' @param setProps Dash-assigned callback that should be called whenever any of the properties change 

DashColorscales <- function(id = NULL, colorscale = NULL, nSwatches = NULL, fixSwatches = NULL, setProps = NULL) {

component <- list(
  props = list(
    id=id, 
				colorscale=colorscale, 
				nSwatches=nSwatches, 
				fixSwatches=fixSwatches, 
				setProps=setProps
  ),
  type = 'DashColorscales',
  namespace = 'dash_colorscales',
  propNames = c('id', 'colorscale', 'nSwatches', 'fixSwatches', 'setProps'),
  package = 'dashColorscales'
)

component$props <- filter_null(component$props)

structure(component, class = c('dash_component', 'list'))
}


filter_null <- function(x) {
  if (length(x) == 0 || !is.list(x)) return(x)
  x[!vapply(x, is.null, logical(1))]
}

assert_valid_children <- function(...) {
  kids <- list(...)
  if (length(kids) == 0) return(NULL)
  assert_no_names(kids)
}

assert_no_names <- function(x) {
  nms <- names(x)
  if (!is.null(nms)) {
    stop(
      sprintf(
        "Didn't recognize the following named arguments: '%s'",
         paste(nms, collapse = "', '")
       ), call. = FALSE
    )
  }
  names(x) <- NULL
  x
}
